### PR TITLE
Update scripts to account for new SITES

### PR DESCRIPTION
**Pull request by melhemr**

### CODE REVIEW

**Comment by melhemr** [comment]
@AbdulkadirA and @rpomponio  can you review the changes we've made and merge if you think this is ready

**Comment by rpomponio** [comment]
Awesome work, @melhemr ! The code looks good to me. Though I'm wondering what additional functionality this accomplishes. Is it the ability to apply the model to new, unseen sites?

If @AbdulkadirA is on board with this, I'm happy to merge right away.

**Comment by AbdulkadirA** [comment]
@rpomponio I am on board with this. And yes, it enables to predict the standardized mean from external data.

**Comment by rpomponio** [comment]
Awesome, I just merged and I am going to update the version number.

**Comment by melhemr** [comment]
Thank you so much Ray! I'm glad I could contribute to the project!

________________________________
From: Raymond Pomponio ***@***.***>
Sent: Tuesday, July 20, 2021 12:20 PM
To: rpomponio/neuroHarmonize ***@***.***>
Cc: Melhem, Randa <Randa.Melhem@Pennmedicine.upenn.edu>; Mention ***@***.***>
Subject: [External] Re: [rpomponio/neuroHarmonize] Update scripts to account for new SITES (#9)


Awesome, I just merged and I am going to update the version number.

**Pull request merged**
